;
; File generated by cc65 v 2.19 - Git 855808faf
;
	.fopt		compiler,"cc65 v 2.19 - Git 855808faf"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_strcat
	.import		_itoa
	.import		_print
	.export		_buf
	.export		_main

.segment	"RODATA"

S0001:
	.byte	$0A,$00

.segment	"BSS"

_buf:
	.res	16,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; itoa(42, buf, 10) ;
;
	lda     #$2A
	jsr     pusha0
	lda     #<(_buf)
	ldx     #>(_buf)
	jsr     pushax
	ldx     #$00
	lda     #$0A
	jsr     _itoa
;
; strcat(buf, "\n") ;
;
	lda     #<(_buf)
	ldx     #>(_buf)
	jsr     pushax
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     _strcat
;
; print(buf) ;
;
	lda     #<(_buf)
	ldx     #>(_buf)
	jsr     _print
;
; return 0 ;
;
	ldx     #$00
	txa
;
; }
;
	rts

.endproc

