;
; File generated by cc65 v 2.19 - Git 855808faf
;
	.fopt		compiler,"cc65 v 2.19 - Git 855808faf"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_stdout
	.import		_stderr
	.import		_fprintf
	.import		_printf
	.export		_main

.segment	"RODATA"

S0002:
	.byte	$73,$74,$64,$6F,$75,$74,$20,$76,$69,$61,$20,$66,$64,$0A,$00
S0003:
	.byte	$73,$74,$64,$65,$72,$72,$20,$76,$69,$61,$20,$66,$64,$0A,$00
S0001:
	.byte	$73,$74,$64,$6F,$75,$74,$3A,$20,$25,$64,$0A,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; printf("stdout: %d\n", 134 / 56) ;
;
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	lda     #$02
	jsr     pusha0
	ldy     #$04
	jsr     _printf
;
; fprintf(stdout, "stdout via fd\n") ;
;
	lda     _stdout
	ldx     _stdout+1
	jsr     pushax
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	ldy     #$04
	jsr     _fprintf
;
; fprintf(stderr, "stderr via fd\n") ;
;
	lda     _stderr
	ldx     _stderr+1
	jsr     pushax
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     pushax
	ldy     #$04
	jsr     _fprintf
;
; return 0 ;
;
	ldx     #$00
	txa
;
; }
;
	rts

.endproc

