;
; File generated by cc65 v 2.19 - Git 855808faf
;
	.fopt		compiler,"cc65 v 2.19 - Git 855808faf"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch

