;
; File generated by cc65 v 2.19 - Git 855808faf
;
	.fopt		compiler,"cc65 v 2.19 - Git 855808faf"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_fprint
	.export		_print

; ---------------------------------------------------------------
; void __near__ fprint (unsigned int fd, char *str)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fprint: near

.segment	"CODE"

	jsr     pushax
	jsr     push0
	jmp     L0004
L0002:	ldy     #$05
	jsr     ldaxysp
	sta     sreg
	stx     sreg+1
	jsr     ldax0sp
	clc
	ldy     #$02
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	sta     (sreg),y
	ldx     #$00
	lda     #$01
	jsr     addeq0sp
L0004:	jsr     ldax0sp
	clc
	ldy     #$02
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$00
	lda     (ptr1),y
	bne     L0002
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; void __near__ print (char *str)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_print: near

.segment	"CODE"

	jsr     pushax
	ldx     #$FF
	lda     #$F1
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	jsr     _fprint
	jmp     incsp2

.endproc

